name: SAST

on:
  push:
    branches: [ main ]

jobs:
  ws-sast:
    name: WS-SAST
    runs-on: ubuntu-latest
    env:
      SAST_ORGANIZATION: ${{secrets.SAST_ORGANIZATION}}
      SASTCLI_TOKEN: ${{secrets.SASTCLI_TOKEN}}
      SAST_SERVER: https://saas.whitesourcesoftware.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Download CLI
      - name: Download CLI
        run: curl -LJO https://downloads.mend.io/cli/linux_amd64/mend && chmod +x mend
      # Run CLI
      - name: Run WS-SAST
        run: ./mend code --dir ./ --name=${{github.event.repository.name}}-${{github.ref_name}}-${{github.sha}} --app=${{github.event.repository.name}} --baseline=true
